set tabstop=4
set shiftwidth=4
set expandtab
set wrap
set mouse=a
set number
syntax on
colorscheme pablo
let g:netrw_dirhistmax = 0


" VIMSCRIPT ----------------------------------------- {{{

" Enable code folding
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

"}}}


